export const DELETE_BLOG_POST = "DELETE BLOG POST";
export const CREATE_BLOG_POST = "CREATE BLOG POST";
export const EDIT_BLOG_POST = "EDIT BLOG POST";

// JSON Server Actions
export const GET_BLOG_POST = "GET BLOG POST";
export const CREATE_BLOG_POST_ON_SERVER = "CREATE BLOG POST ON SERVER";
export const DELETE_BLOG_POST_ON_SERVER = "DELETE BLOG POST ON SERVER";
export const EDIT_BLOG_POST_ON_SERVER = "EDIT BLOG POST ON SERVER";
